# This is a basic workflow to help you get started with Actions

name: Pontoon Build Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup local.properties file
        run:  touch local.properties
      - name: Pull google services json
        uses: keithweaver/aws-s3-github-action@master
        with:
          command: cp
          source: ${{ secrets.DEBUG_GOOGLE_SERVICES_JSON }}
          destination: ./app/google-services.json
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build the app
        run: ./gradlew build test
      - name: Build apk
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
