name: Pontoon Pull Request Workflow
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup local.properties file
        run: |
          touch local.properties
      - name: Test & build apk
        run: ./gradlew clean test assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
