# This is a basic workflow to help you get started with Actions
name: Pontoon Release Workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pulling keystore from aws
      uses: prewk/s3-cp-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE: '${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }}'
          DEST: './keystore.jks'
      - name: pulling x from aws
      uses: prewk/s3-cp-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE: '${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }}'
          DEST: './app/google-services.json'
      - name: pulling x from aws
      uses: prewk/s3-cp-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE: '${{ secrets.RELEASE_GOOGLE_SERVICES_JSON }}'
          DEST: './app/google-services.json'
      - name: Setup local.properties file
        run:  touch local.properties
      - name: Build the app
        run: ./gradlew build test
      - name: Build apk
        run: ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
